---
kind: pipeline
name: python-3.7

steps:
  - name: test
    image: python:3.7
    environment:
      CGTWQ_TEST_ACCOUNT:
        from_secret: "CGTWQ_TEST_ACCOUNT"
      CGTWQ_TEST_PASSWORD:
        from_secret: "CGTWQ_TEST_PASSWORD"
      # PIP_INDEX_URL: https://mirrors.aliyun.com/pypi/simple/
      TOXENV: py37
    commands:
      - pip install -U pip virtualenv
      - make test
---
kind: pipeline
name: python-3.6

steps:
  - name: test
    image: python:3.6
    environment:
      CGTWQ_TEST_ACCOUNT:
        from_secret: "CGTWQ_TEST_ACCOUNT"
      CGTWQ_TEST_PASSWORD:
        from_secret: "CGTWQ_TEST_PASSWORD"
      # PIP_INDEX_URL: https://mirrors.aliyun.com/pypi/simple/
      TOXENV: py36
    commands:
      - pip install -U pip virtualenv
      - make test
depends_on:
  - python-3.7
---
kind: pipeline
name: python-2.7

steps:
  - name: test
    image: python:2.7
    environment:
      CGTWQ_TEST_ACCOUNT:
        from_secret: "CGTWQ_TEST_ACCOUNT"
      CGTWQ_TEST_PASSWORD:
        from_secret: "CGTWQ_TEST_PASSWORD"
      # PIP_INDEX_URL: https://mirrors.aliyun.com/pypi/simple/
      TOXENV: py27
    commands:
      - pip install -U pip virtualenv
      - make test
depends_on:
  - python-3.6
---
kind: pipeline
name: notification

clone:
  disable: true
steps:
  - name: youdu
    image: registry.wlf.com/drone-youdu
    failure: ignore
    settings:
      url:
        from_secret: YOUDU_URL
      buin:
        from_secret: YOUDU_BUIN
      app_id:
        from_secret: YOUDU_APP_ID
      aes_key:
        from_secret: YOUDU_AES_KEY
      from:
        from_secret: YOUDU_FROM
      to:
        from_secret: YOUDU_TO
depends_on:
  - python-3.7
  - python-3.6
  - python-2.7
trigger:
  status:
    - success
    - failure
