language: python
python:
  - "2.7"
addons:
  apt:
    update: true
install:
  - yes "" | sudo add-apt-repository ppa:mc3man/trusty-media &&
    sudo apt-get update &&
    sudo apt-get install ffmpeg && ffmpeg -version
  - pip install pipenv && pipenv --version
  - pipenv install -v --system
  - pip install coverage pytest
cache:
  - pip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run -m pytest tests
after_script:
  - coverage xml && coverage report
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT