# -*- coding=UTF-8 -*-
# Code generated by scripts\python-version-updater.js, DO NOT EDIT
"""
version info.
"""

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from datetime import datetime

VERSION = '3.0.0'
RELEASE_DATE = datetime.fromtimestamp(1615459220)
LAST_GIT_COMMIT_DESCRIBE = 'v3.0.0-beta.4-14-ga72089f'
LAST_GIT_COMMIT_HASH = 'a72089f3804217765572528f4eb601650b0b44ec'
LAST_GIT_COMMIT_AUTHOR_NAME = 'NateScarlet'
LAST_GIT_COMMIT_AUTHOR_EMAIL = 'NateScarlet@Gmail.com'
LAST_GIT_COMMIT_AUTHOR_DATE = datetime.fromtimestamp(1615459048)
LAST_GIT_COMMIT_SUBJECT = 'chore: remove unused file'
LAST_GIT_COMMIT_BODY = ''
