# -*- coding=UTF-8 -*-
# Code generated by scripts\python-version-updater.js, DO NOT EDIT
"""
version info.
"""

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from datetime import datetime

VERSION = '3.0.3'
RELEASE_DATE = datetime.fromtimestamp(1616137293)
LAST_GIT_COMMIT_DESCRIBE = 'v3.0.2-1-gfc2d5ed'
LAST_GIT_COMMIT_HASH = 'fc2d5edc35dbfeb61d0b91ea066acfc51094cf39'
LAST_GIT_COMMIT_AUTHOR_NAME = 'NateScarlet'
LAST_GIT_COMMIT_AUTHOR_EMAIL = 'NateScarlet@Gmail.com'
LAST_GIT_COMMIT_AUTHOR_DATE = datetime.fromtimestamp(1616137095)
LAST_GIT_COMMIT_SUBJECT = 'refactor(deps): replace package `wlf`'
LAST_GIT_COMMIT_BODY = 'with `pathlib2-unicode` + `deprecated` + `cast-unknown`'
