# -*- coding=UTF-8 -*-
# Code generated by scripts\python-version-updater.js, DO NOT EDIT
"""
version info.
"""

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from datetime import datetime

VERSION = '3.6.1'
RELEASE_DATE = datetime.fromtimestamp(1639552001)
LAST_GIT_COMMIT_DESCRIBE = 'v3.6.0-1-g8fe8afc'
LAST_GIT_COMMIT_HASH = '8fe8afc1c9b8535bb2ba9ef4e1917a07673ef045'
LAST_GIT_COMMIT_AUTHOR_NAME = 'NateScarlet'
LAST_GIT_COMMIT_AUTHOR_EMAIL = 'NateScarlet@Gmail.com'
LAST_GIT_COMMIT_AUTHOR_DATE = datetime.fromtimestamp(1639551965)
LAST_GIT_COMMIT_SUBJECT = 'fix: should import configparser from six'
LAST_GIT_COMMIT_BODY = ''
